source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Moya'
pod 'Moya/RxSwift'
pod 'Argo'
pod 'Curry'
pod 'Kingfisher', '~> 2.2'
pod 'MJRefresh'
pod 'BTNavigationDropdownMenu'
pod 'Armchair', '~> 0.1.1'
pod 'Fabric'
pod 'Crashlytics'